services:
  - type: web
    name: achou-pet-backend
    env: python
    region: oregon  # ou outra região, se quiser mudar
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: daphne -b 0.0.0.0 -p $PORT config.asgi:application
    plan: free  # ou starter, se quiser mais performance
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        sync: false  # você deve setar manualmente no painel do Render
      - key: ALLOWED_HOSTS
        value: achou-pet.onrender.com,localhost,127.0.0.1
      - key: IPINFO_TOKEN
        sync: false  # se você usa geolocalização
      - key: DATABASE_URL
        fromDatabase:
          name: achou-pet-db
