services:
  - type: web
    name: achou-pet-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: daphne -b 0.0.0.0 -p $PORT config.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: achou-pet.onrender.com,localhost,127.0.0.1
      - key: IPINFO_TOKEN
        sync: false
      - key: LOCATIONIQ_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: achou-pet-db
      - key: CLOUD_NAME
        sync: false
      - key: CLOUD_API_KEY
        sync: false
      - key: CLOUD_API_SECRET
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
