# Generated by Django 5.1.6 on 2025-03-03 20:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('lost', 'Perdido'), ('found', 'Encontrado')], default='lost', max_length=10)),
                ('species', models.CharField(choices=[('cat', 'Gato'), ('dog', 'Cachorro')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('notification_phone', models.CharField(help_text='Telefone para contato', max_length=15)),
                ('size', models.CharField(choices=[('small', 'Pequeno'), ('medium', 'Médio'), ('large', 'Grande')], max_length=10)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Macho'), ('female', 'Fêmea')], max_length=10)),
                ('lost_date', models.DateField(default=django.utils.timezone.now)),
                ('lost_location', models.CharField(help_text='Endereço onde o pet foi perdido', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='lost_pets/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='lost_pets/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='lost_pets/')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('privacy_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
