# Generated by Django 5.1.6 on 2025-04-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedingpet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='coat_type',
            field=models.CharField(blank=True, choices=[('curto', 'Curto'), ('medio', 'Médio'), ('longo', 'Longo'), ('hairless', 'Sem Pelo')], max_length=20, null=True, verbose_name='Tipo de Pelagem'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('castanho', 'Castanho'), ('azul', 'Azul'), ('verde', 'Verde'), ('amber', 'Âmbar'), ('cinza', 'Cinza'), ('outro', 'Outro')], max_length=20, null=True, verbose_name='Cor dos Olhos'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='coat_type',
            field=models.CharField(blank=True, choices=[('curto', 'Curto'), ('medio', 'Médio'), ('longo', 'Longo'), ('hairless', 'Sem Pelo')], max_length=20, null=True, verbose_name='Tipo de Pelagem'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('castanho', 'Castanho'), ('azul', 'Azul'), ('verde', 'Verde'), ('amber', 'Âmbar'), ('cinza', 'Cinza'), ('outro', 'Outro')], max_length=20, null=True, verbose_name='Cor dos Olhos'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='sex',
            field=models.CharField(choices=[('macho', 'Macho'), ('femea', 'Fêmea')], max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='size',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=10, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='species',
            field=models.CharField(choices=[('gato', 'Gato'), ('dog', 'Cachorro')], max_length=10, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='status',
            field=models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado')], default='lost', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='coat_type',
            field=models.CharField(blank=True, choices=[('curto', 'Curto'), ('medio', 'Médio'), ('longo', 'Longo'), ('hairless', 'Sem Pelo')], max_length=20, null=True, verbose_name='Tipo de Pelagem'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('castanho', 'Castanho'), ('azul', 'Azul'), ('verde', 'Verde'), ('amber', 'Âmbar'), ('cinza', 'Cinza'), ('outro', 'Outro')], max_length=20, null=True, verbose_name='Cor dos Olhos'),
        ),
    ]
