# Generated by Django 5.1.6 on 2025-04-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_registration', '0003_alter_lostpet_photo_1_alter_lostpet_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpet',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='lost_pets/', verbose_name='Foto 1'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='lost_pets/', verbose_name='Foto 2'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='lost_pets/', verbose_name='Foto 3'),
        ),
    ]
