# Generated by Django 5.1.6 on 2025-03-06 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_registration', '0003_alter_petadoption_owner_alter_petadoption_photo_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='breeding', editable=False, max_length=20)),
                ('pet_name', models.CharField(max_length=100)),
                ('approximate_age', models.CharField(max_length=50)),
                ('is_neutered', models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=10)),
                ('approximate_weight', models.CharField(blank=True, max_length=50, null=True)),
                ('is_vaccinated', models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=10)),
                ('health_issues', models.TextField(blank=True, help_text='Problemas de saúde ou necessidades especiais', null=True)),
                ('has_pedigree', models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=10)),
                ('pedigree_details', models.TextField(blank=True, help_text='Detalhes do pedigree ou registro', null=True)),
                ('has_bred_before', models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=10)),
                ('breeding_history', models.TextField(blank=True, help_text='Detalhes de cruzamentos anteriores', null=True)),
                ('breeding_reason', models.TextField(help_text='Motivo do cruzamento (ex: reprodução de raça pura, melhoria genética)')),
                ('puppy_preferences', models.TextField(blank=True, help_text='Interesse em filhotes específicos (quantidade, sexo, etc.)', null=True)),
                ('cost_sharing', models.TextField(blank=True, help_text='Disposição para compartilhar custos (exames, cuidados pós-parto)', null=True)),
                ('location', models.CharField(help_text='Endereço onde o pet está localizado', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='breeding_photos/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='breeding_photos/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='breeding_photos/')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
