# Generated by Django 5.1.6 on 2025-04-23 22:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_registration', '0004_alter_lostpet_photo_1_alter_lostpet_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpet',
            name='photo_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto 1'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='photo_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto 2'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='photo_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto 3'),
        ),
    ]
