# Generated by Django 5.1.6 on 2025-03-19 22:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_registration', '0005_alter_breedingpet_photo_1_alter_breedingpet_photo_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breedingpet',
            options={'verbose_name': 'Pet para Reprodução', 'verbose_name_plural': 'Pets para Reprodução'},
        ),
        migrations.AlterModelOptions(
            name='lostpet',
            options={'verbose_name': 'Pet Perdido', 'verbose_name_plural': 'Pets Perdidos'},
        ),
        migrations.AlterModelOptions(
            name='petadoption',
            options={'verbose_name': 'Pet para Adoção', 'verbose_name_plural': 'Pets para Adoção'},
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='approximate_age',
            field=models.CharField(max_length=50, verbose_name='Idade Aproximada'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='approximate_weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Peso Aproximado'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='breeding_history',
            field=models.TextField(blank=True, help_text='Detalhes de cruzamentos anteriores', null=True, verbose_name='Histórico de Cruzamento'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='breeding_reason',
            field=models.TextField(help_text='Motivo do cruzamento (ex: reprodução de raça pura, melhoria genética)', verbose_name='Motivo do Cruzamento'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='cost_sharing',
            field=models.TextField(blank=True, help_text='Disposição para compartilhar custos (exames, cuidados pós-parto)', null=True, verbose_name='Divisão de Custos'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='has_bred_before',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=10, verbose_name='Já Cruzou Antes'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='has_pedigree',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=10, verbose_name='Possui Pedigree'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='health_issues',
            field=models.TextField(blank=True, help_text='Problemas de saúde ou necessidades especiais', null=True, verbose_name='Problemas de Saúde'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='is_neutered',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=10, verbose_name='Castrado'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='is_vaccinated',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=10, verbose_name='Vacinado'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='location',
            field=models.CharField(help_text='Endereço onde o pet está localizado', max_length=255, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_pets', to=settings.AUTH_USER_MODEL, verbose_name='Dono'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='pedigree_details',
            field=models.TextField(blank=True, help_text='Detalhes do pedigree ou registro', null=True, verbose_name='Detalhes do Pedigree'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='pet_name',
            field=models.CharField(max_length=100, verbose_name='Nome do Pet'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='breeding_pets/', verbose_name='Foto 1'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='breeding_pets/', verbose_name='Foto 2'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='breeding_pets/', verbose_name='Foto 3'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=False, verbose_name='Privacidade Aceita'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='puppy_preferences',
            field=models.TextField(blank=True, help_text='Interesse em filhotes específicos (quantidade, sexo, etc.)', null=True, verbose_name='Preferências de Filhotes'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='status',
            field=models.CharField(default='breeding', editable=False, max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='breedingpet',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Termos Aceitos'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='color',
            field=models.CharField(max_length=100, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='lost_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Perda'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='lost_location',
            field=models.CharField(help_text='Endereço onde o pet foi perdido', max_length=255, verbose_name='Local de Perda'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='notification_phone',
            field=models.CharField(help_text='Telefone para contato', max_length=15, verbose_name='Telefone de Notificação'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='lost_pets/', verbose_name='Foto 1'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='lost_pets/', verbose_name='Foto 2'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='lost_pets/', verbose_name='Foto 3'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='privacy_accepted',
            field=models.BooleanField(default=False, verbose_name='Privacidade Aceita'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='sex',
            field=models.CharField(choices=[('male', 'Macho'), ('female', 'Fêmea')], max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='size',
            field=models.CharField(choices=[('small', 'Pequeno'), ('medium', 'Médio'), ('large', 'Grande')], max_length=10, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='species',
            field=models.CharField(choices=[('cat', 'Gato'), ('dog', 'Cachorro')], max_length=10, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='status',
            field=models.CharField(choices=[('lost', 'Perdido'), ('found', 'Encontrado')], default='lost', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Termos Aceitos'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_pets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='approximate_age',
            field=models.CharField(max_length=50, verbose_name='Idade Aproximada'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='approximate_weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Peso Aproximado'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='behavior',
            field=models.CharField(help_text='Ex: Medroso, Agitado, Calmo, etc.', max_length=100, verbose_name='Comportamento'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='health_issues',
            field=models.TextField(blank=True, help_text='Problemas de saúde ou necessidades especiais', null=True, verbose_name='Problemas de Saúde'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='is_neutered',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=10, verbose_name='Castrado'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='is_vaccinated',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=10, verbose_name='Vacinado'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='location',
            field=models.CharField(help_text='Endereço onde o pet está localizado', max_length=255, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='observations',
            field=models.TextField(blank=True, help_text='Observações ou cuidados especiais', null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_pets', to=settings.AUTH_USER_MODEL, verbose_name='Dono'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='pet_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Pet'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='adoption_pets/', verbose_name='Foto 1'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='adoption_pets/', verbose_name='Foto 2'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='adoption_pets/', verbose_name='Foto 3'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=False, verbose_name='Privacidade Aceita'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='relationship_with_pet',
            field=models.CharField(choices=[('owner', 'Dono'), ('temporary_caretaker', 'Cuidador Temporário'), ('rescuer', 'Responsável pelo Resgate')], max_length=50, verbose_name='Relação com o Pet'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='sociable_with_animals',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não'), ('sometimes', 'Às Vezes')], max_length=20, verbose_name='Sociável com Animais'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='sociable_with_children',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não'), ('sometimes', 'Às Vezes')], max_length=20, verbose_name='Sociável com Crianças'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='sociable_with_strangers',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não'), ('sometimes', 'Às Vezes')], max_length=20, verbose_name='Sociável com Estranhos'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='status',
            field=models.CharField(default='adoption', editable=False, max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Termos Aceitos'),
        ),
    ]
