# Generated by Django 5.1.6 on 2025-03-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_registration', '0006_alter_breedingpet_options_alter_lostpet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True, verbose_name='Longitude'),
        ),
    ]
