# Generated by Django 5.1.6 on 2025-03-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_registration', '0009_alter_lostpet_latitude_alter_lostpet_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Longitude'),
        ),
    ]
