# Generated by Django 5.1.6 on 2025-03-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_registration', '0010_alter_lostpet_latitude_alter_lostpet_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petadoption',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
