# Generated by Django 5.1.6 on 2025-03-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_registration', '0011_alter_petadoption_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petadoption',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raça'),
        ),
        migrations.AddField(
            model_name='petadoption',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='petadoption',
            name='phone_for_notifications',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone para Notificações'),
        ),
        migrations.AddField(
            model_name='petadoption',
            name='sex',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('fêmea', 'Fêmea')], max_length=6, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='petadoption',
            name='size_by_age',
            field=models.CharField(blank=True, choices=[('filhote', 'Filhote'), ('adulto', 'Adulto'), ('idoso', 'Idoso')], max_length=7, null=True, verbose_name='Tamanho por Idade'),
        ),
        migrations.AddField(
            model_name='petadoption',
            name='species',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
