# -*- coding: utf-8 -*-

# Raças de Gatos
BREEDS_CATS = [
    ('', 'Selecione uma raça'),
    ('sem_raca_definida', 'Sem Raça Definida'),
    ('abissinio', 'Abissínio'),
    ('american_bobtail', 'American Bobtail'),
    ('american_curl', 'American Curl'),
    ('american_shorthair', 'American Shorthair'),
    ('angora_turco', 'Angorá Turco'),
    ('azul_russo', 'Azul Russo'),
    ('balines', 'Balinês'),
    ('bengal', 'Bengal'),
    ('birmanes', 'Birmanês'),
    ('bombay', 'Bombay'),
    ('british_shorthair', 'British Shorthair'),
    ('burmes', 'Burmês'),
    ('burmilla', 'Burmilla'),
    ('chartreux', 'Chartreux'),
    ('chausie', 'Chausie'),
    ('cornish_rex', 'Cornish Rex'),
    ('devon_rex', 'Devon Rex'),
    ('donskoy', 'Donskoy'),
    ('mau_egipcio', 'Mau Egípcio'),
    ('shorthair_exotico', 'Shorthair Exótico'),
    ('himalaio', 'Himalaio'),
    ('japanese_bobtail', 'Japanese Bobtail'),
    ('javanes', 'Javanês'),
    ('korat', 'Korat'),
    ('khao_manee', 'Khao Manee'),
    ('kurilian_bobtail', 'Kurilian Bobtail'),
    ('laperm', 'LaPerm'),
    ('lykoi', 'Lykoi'),
    ('maine_coon', 'Maine Coon'),
    ('manx', 'Manx'),
    ('munchkin', 'Munchkin'),
    ('nebelung', 'Nebelung'),
    ('floresta_norueguesa', 'Floresta Norueguesa'),
    ('ocicat', 'Ocicat'),
    ('oriental', 'Oriental'),
    ('persa', 'Persa'),
    ('peterbald', 'Peterbald'),
    ('pixie_bob', 'Pixie-Bob'),
    ('ragdoll', 'Ragdoll'),
    ('savannah', 'Savannah'),
    ('scottish_fold', 'Scottish Fold'),
    ('selkirk_rex', 'Selkirk Rex'),
    ('siames', 'Siamês'),
    ('siberiano', 'Siberiano'),
    ('singapura', 'Singapura'),
    ('somali', 'Somali'),
    ('sphynx', 'Sphynx'),
    ('tonquines', 'Tonquinês'),
    ('toyger', 'Toyger'),
    ('turco_van', 'Turco Van'),
    ('outro', 'Outro')
]

# Raças de Cachorros
BREEDS_DOGS = [
    ('', 'Selecione uma raça'),
    ('sem_raca_definida', 'Sem Raça Definida'),
    ('affenpinscher', 'Affenpinscher'),
    ('afghan_hound', 'Afghan Hound'),
    ('airedale_terrier', 'Airedale Terrier'),
    ('akita', 'Akita'),
    ('alaskan_klee_kai', 'Alaskan Klee Kai'),
    ('alaskan_malamute', 'Alaskan Malamute'),
    ('american_bulldog', 'American Bulldog'),
    ('american_eskimo_dog', 'American Eskimo Dog'),
    ('american_foxhound', 'American Foxhound'),
    ('american_hairless_terrier', 'American Hairless Terrier'),
    ('american_leopard_hound', 'American Leopard Hound'),
    ('american_pit_bull_terrier', 'American Pit Bull Terrier'),
    ('american_staffordshire_terrier', 'American Staffordshire Terrier'),
    ('american_water_spaniel', 'American Water Spaniel'),
    ('anatolian_shepherd', 'Anatolian Shepherd'),
    ('appenzeller_sennenhund', 'Appenzeller Sennenhund'),
    ('australian_cattle_dog', 'Australian Cattle Dog'),
    ('australian_shepherd', 'Australian Shepherd'),
    ('australian_terrier', 'Australian Terrier'),
    ('azawakh', 'Azawakh'),
    ('barbet', 'Barbet'),
    ('basenji', 'Basenji'),
    ('basset_hound', 'Basset Hound'),
    ('beagle', 'Beagle'),
    ('bearded_collie', 'Bearded Collie'),
    ('bedlington_terrier', 'Bedlington Terrier'),
    ('belgian_laekenois', 'Belgian Laekenois'),
    ('belgian_malinois', 'Belgian Malinois'),
    ('belgian_sheepdog', 'Belgian Sheepdog'),
    ('belgian_tervuren', 'Belgian Tervuren'),
    ('bergamasco_sheepdog', 'Bergamasco Sheepdog'),
    ('bernese_mountain_dog', 'Bernese Mountain Dog'),
    ('bichon_frise', 'Bichon Frise'),
    ('biewer_terrier', 'Biewer Terrier'),
    ('black_and_tan_coonhound', 'Black and Tan Coonhound'),
    ('black_russian_terrier', 'Black Russian Terrier'),
    ('bloodhound', 'Bloodhound'),
    ('bluetick_coonhound', 'Bluetick Coonhound'),
    ('boerboel', 'Boerboel'),
    ('bohemian_shepherd', 'Bohemian Shepherd'),
    ('bolognese', 'Bolognese'),
    ('border_collie', 'Border Collie'),
    ('border_terrier', 'Border Terrier'),
    ('borzoi', 'Borzoi'),
    ('boston_terrier', 'Boston Terrier'),
    ('bouvier_des_flandres', 'Bouvier des Flandres'),
    ('boxer', 'Boxer'),
    ('boykin_spaniel', 'Boykin Spaniel'),
    ('bracco_italiano', 'Bracco Italiano'),
    ('briard', 'Briard'),
    ('brittany', 'Brittany'),
    ('brussels_griffon', 'Brussels Griffon'),
    ('bull_terrier', 'Bull Terrier'),
    ('bulldog', 'Bulldog'),
    ('bullmastiff', 'Bullmastiff'),
    ('cairn_terrier', 'Cairn Terrier'),
    ('canaan_dog', 'Canaan Dog'),
    ('cane_corso', 'Cane Corso'),
    ('cardigan_welsh_corgi', 'Cardigan Welsh Corgi'),
    ('cavalier_king_charles_spaniel', 'Cavalier King Charles Spaniel'),
    ('cesky_terrier', 'Cesky Terrier'),
    ('chesapeake_bay_retriever', 'Chesapeake Bay Retriever'),
    ('chihuahua', 'Chihuahua'),
    ('chinese_crested', 'Chinese Crested'),
    ('chinese_shar_pei', 'Chinese Shar-Pei'),
    ('chow_chow', 'Chow Chow'),
    ('clumber_spaniel', 'Clumber Spaniel'),
    ('cocker_spaniel', 'Cocker Spaniel'),
    ('collie', 'Collie'),
    ('coton_de_tulear', 'Coton de Tulear'),
    ('curly_coated_retriever', 'Curly-Coated Retriever'),
    ('dachshund', 'Dachshund'),
    ('dalmatian', 'Dalmatian'),
    ('dandie_dinmont_terrier', 'Dandie Dinmont Terrier'),
    ('doberman_pinscher', 'Doberman Pinscher'),
    ('dogo_argentino', 'Dogo Argentino'),
    ('dutch_shepherd', 'Dutch Shepherd'),
    ('english_cocker_spaniel', 'English Cocker Spaniel'),
    ('english_foxhound', 'English Foxhound'),
    ('english_setter', 'English Setter'),
    ('english_springer_spaniel', 'English Springer Spaniel'),
    ('english_toy_spaniel', 'English Toy Spaniel'),
    ('entlebucher_mountain_dog', 'Entlebucher Mountain Dog'),
    ('field_spaniel', 'Field Spaniel'),
    ('finnish_lapphund', 'Finnish Lapphund'),
    ('finnish_spitz', 'Finnish Spitz'),
    ('flat_coated_retriever', 'Flat-Coated Retriever'),
    ('french_bulldog', 'French Bulldog'),
    ('french_spaniel', 'French Spaniel'),
    ('german_pinscher', 'German Pinscher'),
    ('german_shepherd', 'German Shepherd'),
    ('german_shorthaired_pointer', 'German Shorthaired Pointer'),
    ('german_wirehaired_pointer', 'German Wirehaired Pointer'),
    ('giant_schnauzer', 'Giant Schnauzer'),
    ('glen_of_imaal_terrier', 'Glen of Imaal Terrier'),
    ('golden_retriever', 'Golden Retriever'),
    ('gordon_setter', 'Gordon Setter'),
    ('great_dane', 'Great Dane'),
    ('great_pyrenees', 'Great Pyrenees'),
    ('greater_swiss_mountain_dog', 'Greater Swiss Mountain Dog'),
    ('greyhound', 'Greyhound'),
    ('harrier', 'Harrier'),
    ('havanese', 'Havanese'),
    ('ibizan_hound', 'Ibizan Hound'),
    ('icelandic_sheepdog', 'Icelandic Sheepdog'),
    ('irish_red_and_white_setter', 'Irish Red and White Setter'),
    ('irish_setter', 'Irish Setter'),
    ('irish_terrier', 'Irish Terrier'),
    ('irish_water_spaniel', 'Irish Water Spaniel'),
    ('irish_wolfhound', 'Irish Wolfhound'),
    ('italian_greyhound', 'Italian Greyhound'),
    ('jack_russell_terrier', 'Jack Russell Terrier'),
    ('japanese_chin', 'Japanese Chin'),
    ('keeshond', 'Keeshond'),
    ('kerry_blue_terrier', 'Kerry Blue Terrier'),
    ('komondor', 'Komondor'),
    ('kuvasz', 'Kuvasz'),
    ('labrador_retriever', 'Labrador Retriever'),
    ('lakeland_terrier', 'Lakeland Terrier'),
    ('lancashire_heeler', 'Lancashire He câ€"Lancashire Heeler'),
    ('leonberger', 'Leonberger'),
    ('lhasa_apso', 'Lhasa Apso'),
    ('lowchen', 'Lowchen'),
    ('maltese', 'Maltese'),
    ('manchester_terrier', 'Manchester Terrier'),
    ('mastiff', 'Mastiff'),
    ('miniature_american_shepherd', 'Miniature American Shepherd'),
    ('miniature_bull_terrier', 'Miniature Bull Terrier'),
    ('miniature_pinscher', 'Miniature Pinscher'),
    ('miniature_schnauzer', 'Miniature Schnauzer'),
    ('mudi', 'Mudi'),
    ('neapolitan_mastiff', 'Neapolitan Mastiff'),
    ('newfoundland', 'Newfoundland'),
    ('norfolk_terrier', 'Norfolk Terrier'),
    ('norwegian_buhund', 'Norwegian Buhund'),
    ('norwegian_elkhound', 'Norwegian Elkhound'),
    ('norwegian_lundehund', 'Norwegian Lundehund'),
    ('norwich_terrier', 'Norwich Terrier'),
    ('nova_scotia_duck_tolling_retriever', 'Nova Scotia Duck Tolling Retriever'),
    ('old_english_sheepdog', 'Old English Sheepdog'),
    ('otterhound', 'Otterhound'),
    ('papillon', 'Papillon'),
    ('parson_russell_terrier', 'Parson Russell Terrier'),
    ('pekingese', 'Pekingese'),
    ('pembroke_welsh_corgi', 'Pembroke Welsh Corgi'),
    ('petit_basset_griffon_vendeen', 'Petit Basset Griffon Vendeen'),
    ('pharaoh_hound', 'Pharaoh Hound'),
    ('plott_hound', 'Plott Hound'),
    ('pointer', 'Pointer'),
    ('polish_lowland_sheepdog', 'Polish Lowland Sheepdog'),
    ('pomeranian', 'Pomeranian'),
    ('poodle', 'Poodle'),
    ('portuguese_podengo_pequeno', 'Portuguese Podengo Pequeno'),
    ('portuguese_water_dog', 'Portuguese Water Dog'),
    ('pug', 'Pug'),
    ('puli', 'Puli'),
    ('pyrenean_mastiff', 'Pyrenean Mastiff'),
    ('pyrenean_shepherd', 'Pyrenean Shepherd'),
    ('rat_terrier', 'Rat Terrier'),
    ('redbone_coonhound', 'Redbone Coonhound'),
    ('rhodesian_ridgeback', 'Rhodesian Ridgeback'),
    ('rottweiler', 'Rottweiler'),
    ('russell_terrier', 'Russell Terrier'),
    ('saint_bernard', 'Saint Bernard'),
    ('saluki', 'Saluki'),
    ('samoyed', 'Samoyed'),
    ('schipperke', 'Schipperke'),
    ('scottish_deerhound', 'Scottish Deerhound'),
    ('scottish_terrier', 'Scottish Terrier'),
    ('sealyham_terrier', 'Sealyham Terrier'),
    ('shetland_sheepdog', 'Shetland Sheepdog'),
    ('shiba_inu', 'Shiba Inu'),
    ('shih_tzu', 'Shih Tzu'),
    ('siberian_husky', 'Siberian Husky'),
    ('silky_terrier', 'Silky Terrier'),
    ('sky_terrier', 'Sky Terrier'),
    ('sloughi', 'Sloughi'),
    ('small_munsterlander', 'Small Munsterlander'),
    ('soft_coated_wheaten_terrier', 'Soft Coated Wheaten Terrier'),
    ('spanish_water_dog', 'Spanish Water Dog'),
    ('spinone_italiano', 'Spinone Italiano'),
    ('staffordshire_bull_terrier', 'Staffordshire Bull Terrier'),
    ('standard_schnauzer', 'Standard Schnauzer'),
    ('sussex_spaniel', 'Sussex Spaniel'),
    ('swedish_lapphund', 'Swedish Lapphund'),
    ('swedish_vallhund', 'Swedish Vallhund'),
    ('tibetan_mastiff', 'Tibetan Mastiff'),
    ('tibetan_spaniel', 'Tibetan Spaniel'),
    ('tibetan_terrier', 'Tibetan Terrier'),
    ('toy_fox_terrier', 'Toy Fox Terrier'),
    ('treeing_walker_coonhound', 'Treeing Walker Coonhound'),
    ('vizsla', 'Vizsla'),
    ('weimaraner', 'Weimaraner'),
    ('welsh_springer_spaniel', 'Welsh Springer Spaniel'),
    ('welsh_terrier', 'Welsh Terrier'),
    ('west_highland_white_terrier', 'West Highland White Terrier'),
    ('whippet', 'Whippet'),
    ('wire_fox_terrier', 'Wire Fox Terrier'),
    ('wirehaired_pointing_griffon', 'Wirehaired Pointing Griffon'),
    ('wirehaired_vizsla', 'Wirehaired Vizsla'),
    ('xoloitzcuintli', 'Xoloitzcuintli'),
    ('yorkshire_terrier', 'Yorkshire Terrier'),
    ('outro', 'Outro')
]
